### ISSUE TITLE
Performance Issues with Lemmatization

### ISSUE THREAD

**Issue by programminghumanity** [berknology/text-preprocessing#1]
I'm encountering a very slow processing time on a Pandas DataFrame of ~40k sentences (generally short to mid-length extracted from TV dialog).

It appears to be doing 4k sentences/10mins on a GPU/High-Memory Pro Google Colab notebook.  This may be normal or infact good. It seems to be 2x the speed of the SpaCy pipeline specs here:

https://stackoverflow.com/questions/51372724/how-to-speed-up-spacy-lemmatization

Any guidance on speeding up this processing step would be appreciated. Could this be accelerated with multi-core? Are any config changes required? Any guidelines on breakpoints on memory size of Google Cloud instances that may help?

Great package, long-overdue and very needed. - J

**Comment by berknology** [comment]
Hi J,
     This package is leveraging `WordNetLemmatizer` from the `nltk` package, as you can see from the source code [here](https://github.com/berknology/text-preprocessing/blob/master/text_preprocessing/text_preprocessing.py#L271). If you only need the lemmatization function, you can directly use the `nltk` package. 
    To process large amount of data, you might want to leverage big data solution, such as Spark. Below is an example how you can wrap the code, and run in Spark environment such as Azure Databricks.
     I have no experience with Google cloud, hence I cannot answer your questions about it. 
     
```
from text_preprocessing import preprocess_text
from pyspark.sql.functions import udf
from pyspark.sql.types import StringType
from pyspark.sql import DataFrame as SparkDataFrame


def preprocess_text_spark(df: SparkDataFrame, 
                          target_column: str, 
                          preprocessed_column_name: str = 'preprocessed_text'
                         ) -> SparkDataFrame:
    """ Preprocess text in a column of a PySpark DataFrame by leveraging PySpark UDF to preprocess text in parallel """
    _preprocess_text = udf(preprocess_text, StringType())
    new_df = df.withColumn(preprocessed_column_name, _preprocess_text(df[target_column]))
    return new_df
```

**Comment by berknology** [comment]
Closed issue due to inactivity.
