### ISSUE TITLE
Pass Preprocess_functions as a parameter to udf Preprocess_text method 

### ISSUE THREAD

**Issue by EAAcs** [berknology/text-preprocessing#2]
I would like to pass preprocess_functions as a parameter to preprocess_text method

using the example below

def preprocess_text_spark(df: SparkDataFrame, target_column: str, preprocessed_column_name: str = 'preprocessed_text' ) -> SparkDataFrame:

""" Preprocess text in a column of a PySpark DataFrame by leveraging PySpark UDF to preprocess text in parallel """

preprocess_functions = [to_lower, remove_email, remove_url, remove_punctuation, remove_special_character, normalize_unicode, remove_number, remove_whitespace, remove_stopword, lemmatize_word, stem_word, check_spelling] _preprocess_text = udf(preprocess_text, StringType()) new_df = df.withColumn(preprocessed_column_name, _preprocess_text(df[target_column],preprocess_functions)) return new_df

TypeError: Invalid argument, not a string or column: [<function to_lower at 0x7f33f9a865f0>, <function remove_email at 0x7f33f9a93c20>, <function remove_url at 0x7f33f9a933b0>, <function remove_punctuation at 0x7f33f9a934d0>, <function remove_special_character at 0x7f33f9a935f0>, <function normalize_unicode at 0x7f33f9a93a70>, <function remove_number at 0x7f33f9a93170>, <function remove_whitespace at 0x7f33f9a93830>, <function remove_stopword at 0x7f33f9a93b00>, <function lemmatize_word at 0x7f33f9a8d4d0>, <function stem_word at 0x7f33f9a8d3b0>, <function check_spelling at 0x7f33f9a8d170>] of type <class 'list'>. For column literals, use 'lit', 'array', 'struct' or 'create_map' function.

I tried to convert the preprocess_functions to array and lit with no results

How could I resolve this issue?

https://stackoverflow.com/questions/67561202/pass-list-to-udf-method-as-a-parameter

**Comment by berknology** [comment]
Can you do something like this:
```
from pyspark.sql.functions import udf
from pyspark.sql.types import StringType
from pyspark.sql import DataFrame as SparkDataFrame
from text_preprocessing import *

def custom_preprocess_text(input_text, processing_function_list) -> str:
       return preprocess_text(input_text, processing_function_list)
   

def preprocess_text_spark(df: SparkDataFrame, 
                          target_column: str, 
                          preprocessed_column_name: str = 'preprocessed_text'
                         ) -> SparkDataFrame:
    """ Preprocess text in a column of a PySpark DataFrame by leveraging PySpark UDF to preprocess text in parallel """
   
    _preprocess_text = udf(customer_preprocess_text, StringType())
    new_df = df.withColumn(preprocessed_column_name, _preprocess_text(df[target_column]))
    return new_df
```

**Comment by EAAcs** [comment]
Thanks a lot, it works perfectly
