### ISSUE TITLE
How to cite this GitHub repository

### ISSUE THREAD

**Issue by Tushar-Faroque** [berknology/text-preprocessing#4]
Hello,
Thanks for your contribution. How can I cite your work on my paper?

**Comment by berknology** [comment]
Hi @Tushar-Faroque,
     Thank you very much for interest!
     Personally, I do not need to be cited. But if you would like to cite it in your paper, you could do something like [this](https://academia.stackexchange.com/questions/14010/how-do-you-cite-a-github-repository).
