### ISSUE TITLE
Code breaks when cleaning names

### ISSUE THREAD

**Issue by Jensonah** [berknology/text-preprocessing#6]
The code breaks when "preprocess_text(string)" is called.
The function "name_searcher.search_first_name(token)" specifically breaks. It does not seem to be supported anymore by "names_dataset". Instead in your usecase it could work with just the "search" function.
I.e. -> "name_searcher.search(token)".
I assume the same bug would occur with the last name search.
Thanks in advance

**Comment by berknology** [comment]
Fixed the issue, please check and let me know if the issue persists. Thanks.
