### ISSUE TITLE
names-dataset made breaking chnages

### ISSUE THREAD

**Issue by bnaman50** [berknology/text-preprocessing#8]
Hey team, 

I saw that you are using [`names-dataset`](https://github.com/philipperemy/name-dataset) library and sadly, they made some breaking changes and it gives following error when you run the example given in the Readme - 
`AttributeError: 'NameDataset' object has no attribute 'search_first_name'`

On further [digging](https://github.com/philipperemy/name-dataset/issues/26), I found that they have removed the `search_first_name` method altogether. Now only `search` method is there. 

Could you please update the codebase or maybe specify the library version which included `search_first_name` method? 

Thanks, 
Naman

**Comment by philipperemy** [comment]
@bnaman50 use `names-dataset==2.1`. A breaking change happened in the 3.X version.

**Comment by philipperemy** [comment]
https://github.com/berknology/text-preprocessing/pull/9

**Comment by berknology** [comment]
Fixed the issue, please check and let me know if the issue persists. Thanks.

**Comment by bnaman50** [comment]
Thanks a lot, @berknology. It is working now. 

Naman
